### ISSUE TITLE
Question about day_duration

### ISSUE THREAD

**Issue by mitchcurtis** [hiulit/Godot-3-2D-Day-Night-Cycle#3]
`day_duration` is initially set to minutes:

https://github.com/hiulit/Godot-3-2D-Day-Night-Cycle/blob/bfa41a7978b4ea489b54a0f92c33ef365c1bd76a/DayNightCycle.gd#L3

then it's converted to seconds:

https://github.com/hiulit/Godot-3-2D-Day-Night-Cycle/blob/bfa41a7978b4ea489b54a0f92c33ef365c1bd76a/DayNightCycle.gd#L34

but there are only 60 seconds in a minute, so why does it multiply the result by 60 again?

I ask because I'm currently looking into an issue with my game and to fix it I need to understand this code.

**Comment by mitchcurtis** [comment]
Is it something to do with in-game vs real time? Every second in real life, 60 seconds pass in-game?

**Comment by hiulit** [comment]
Hey, sorry for the late response.

I actually don't have a clue! xD I've looked at the code and tried removing the second `* 60` and everything goes to shit, so I don't know :S

I'll keep looking and I'll also try to play with `delta` to see if I can get better results. I'll keep you posted.

**Comment by mitchcurtis** [comment]
No worries, don't stress about it. :) I had to rewrite the code to work with my game, and in the process changed it quite a bit, but I understand it now.

**Comment by hiulit** [comment]
Would you mind sharing your code with me? Maybe I can improve my code.

**Comment by mitchcurtis** [comment]
Sure, should I push a patch? I factored out the time stuff into a Time class, now DayNightCycle is just tweening the colours.

**Comment by hiulit** [comment]
Yeah, sure. That'd be great. Send me a Pull Request so I can review it.
Thanks!

El dl., 2 de set. 2019, 22:25, mitchcurtis <notifications@github.com> va
escriure:

**Comment by mitchcurtis** [comment]
Here it is: https://github.com/hiulit/Godot-3-2D-Day-Night-Cycle/pull/4

**Comment by hiulit** [comment]
Wow! Thanks! It will take me some time to have a deep look into, but I really appreciate it :)

**Comment by oliviathevampire** [comment]
Any updates? @hiulit

**Comment by hiulit** [comment]
Yeah, @oliviathevampire I'm working on it as I'm typing :)
I should release a new version really soon. I'll let you know.

**Comment by hiulit** [comment]
@oliviathevampire I've just release v3.0.0 :D

**Comment by hiulit** [comment]
@mitchcurtis Thanks! I'll be closing this issue since I've already merge your PR :)
